server:
  port: 8181
  servlet:
    context-path: /app
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus.p12
    key-store-password: 123456
    key-alias: otus
    truststore:
      store: truststore.p12
      password: 123456
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  main:
    web-application-type: none

  sql:
    init:
      platform: postgres
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE